### ISSUE TITLE
upvote/downvote popup/title too big for non logged-in user

### ISSUE THREAD

**Issue by rasocbo** [rasocbo/bublol#32]
![image](https://user-images.githubusercontent.com/68491343/100347766-e0d8a500-300b-11eb-93da-513172046b3a.png)

**Comment by dragosjurca** [comment]
A possible solution:
![Tooltip visitors](https://user-images.githubusercontent.com/45625917/100516960-1d350e00-3190-11eb-8be0-5b044bac5560.png)

**Comment by rasocbo** [comment]
Fixed in #a0b3c78
