### ISSUE TITLE
"Add tag" popup - should it be inline? (instead of a popup)

### ISSUE THREAD

**Issue by rasocbo** [rasocbo/bublol#42]
Currently the "Add tag" button opens a popup:

![image](https://user-images.githubusercontent.com/68491343/101516079-0fa83100-39a5-11eb-8098-47687c975f49.png)

I'm wondering whether it should be inline - besides or beneath the post/comment. 

@dragosjurca, thoughts?

**Comment by dragosjurca** [comment]
I also thought about it at first. It would work well inlined for the initial posts. However, in the comment section, when the threaded tree root becomes very large with numerous replies, the space becomes rather claustrophobic to fit the entire feature under a tiny layout. That’s why I opted for an overlay that behaves the same regardless of its tagging source and gives the user sufficient room to operate it comfortably on any device.

**Comment by rasocbo** [comment]
I see. Good decision.
